--liquibase formatted sql

--changeset batuhan:1
--comment: Initial banking schema creation with preconditions for existing tables
--preconditions onFail:MARK_RAN

-- 1. ADDRESSES TABLE
--precondition-sql-check expectedResult:0 SELECT count(*) FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'addresses'
CREATE TABLE addresses (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           city VARCHAR(100) NOT NULL,
                           street VARCHAR(255) NOT NULL,
                           zip_code VARCHAR(20) NOT NULL,
                           phone_number VARCHAR(50) NOT NULL,
                           is_active BOOLEAN NOT NULL DEFAULT TRUE,
                           created_at TIMESTAMP(6) NOT NULL,
                           updated_at TIMESTAMP(6) NOT NULL
);

-- 2. USERS TABLE
--precondition-sql-check expectedResult:0 SELECT count(*) FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'users'
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       first_name VARCHAR(100) NOT NULL,
                       last_name VARCHAR(100) NOT NULL,
                       email VARCHAR(150) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       tckn VARCHAR(11) NOT NULL UNIQUE,
                       customer_number VARCHAR(20) NOT NULL UNIQUE,
                       birth_date DATE NOT NULL,
                       role VARCHAR(50) NOT NULL,
                       is_active BOOLEAN NOT NULL DEFAULT TRUE,
                       address_id BIGINT UNIQUE,
                       created_at TIMESTAMP(6) NOT NULL,
                       updated_at TIMESTAMP(6) NOT NULL,
                       CONSTRAINT fk_user_address FOREIGN KEY (address_id) REFERENCES addresses(id)
);

-- 3. ACCOUNTS TABLE
--precondition-sql-check expectedResult:0 SELECT count(*) FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'accounts'
CREATE TABLE accounts (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          iban VARCHAR(50) NOT NULL UNIQUE,
                          balance DECIMAL(19, 2) NOT NULL,
                          currency VARCHAR(20) NOT NULL,
                          status VARCHAR(20) NOT NULL,
                          daily_limit DECIMAL(19, 2) NOT NULL,
                          is_active BOOLEAN NOT NULL DEFAULT TRUE,
                          user_id BIGINT NOT NULL,
                          created_at TIMESTAMP(6) NOT NULL,
                          updated_at TIMESTAMP(6) NOT NULL,
                          CONSTRAINT fk_account_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- 4. ACCOUNT_LIMITS TABLE
--precondition-sql-check expectedResult:0 SELECT count(*) FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'account_limits'
CREATE TABLE account_limits (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                account_id BIGINT NOT NULL UNIQUE,
                                daily_limit DECIMAL(19, 2) NOT NULL,
                                used_amount DECIMAL(19, 2) NOT NULL,
                                limit_date DATE NOT NULL,
                                is_active BOOLEAN NOT NULL DEFAULT TRUE,
                                created_at TIMESTAMP(6) NOT NULL,
                                updated_at TIMESTAMP(6) NOT NULL,
                                CONSTRAINT fk_limit_account FOREIGN KEY (account_id) REFERENCES accounts(id)
);

-- 5. TRANSACTIONS TABLE
--precondition-sql-check expectedResult:0 SELECT count(*) FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'transactions'
CREATE TABLE transactions (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              reference_number VARCHAR(100) NOT NULL UNIQUE,
                              amount DECIMAL(19, 2) NOT NULL,
                              transaction_type VARCHAR(50) NOT NULL,
                              status VARCHAR(50) NOT NULL,
                              description VARCHAR(255),
                              sender_account_id BIGINT NOT NULL,
                              receiver_account_id BIGINT NOT NULL,
                              created_at TIMESTAMP(6) NOT NULL,
                              updated_at TIMESTAMP(6) NOT NULL,
                              CONSTRAINT fk_trx_sender FOREIGN KEY (sender_account_id) REFERENCES accounts(id),
                              CONSTRAINT fk_trx_receiver FOREIGN KEY (receiver_account_id) REFERENCES accounts(id)
);

-- 6. AUDIT_LOGS TABLE
--precondition-sql-check expectedResult:0 SELECT count(*) FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'audit_logs'
CREATE TABLE audit_logs (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            action VARCHAR(100),
                            email VARCHAR(150),
                            details TEXT,
                            created_at TIMESTAMP(6) NOT NULL,
                            updated_at TIMESTAMP(6) NOT NULL
);